# Code Snippets to Accompany Linear_Algebra_for_DL.md

In [1]:
import torch
import numpy as np

Main data structures in PyTorch are tensors

In [2]:
a = np.array([1., 2., 3.])
b = torch.tensor([1., 2., 3.])

print(type(a), a.dtype, a.shape)
print(type(b), b.dtype, b.shape)

<class 'numpy.ndarray'> float64 (3,)
<class 'torch.Tensor'> torch.float32 torch.Size([3])


Multiplication (dot-product) has a similar structure between the two libraries

In [3]:
print("numpy 'dot'     -->", a.dot(a))
print("torch 'matmul'  -->", b.matmul(b))

numpy 'dot'     --> 14.0
torch 'matmul'  --> tensor(14.)


There are methods in PyTorch for converting between the two data types

In [4]:
print(type(b.numpy()), b.numpy())               #torch tensor to np array
print(type(torch.tensor(a)), torch.tensor(a))   #np array to torch tensor

<class 'numpy.ndarray'> [1. 2. 3.]
<class 'torch.Tensor'> tensor([1., 2., 3.], dtype=torch.float64)


PyTorch is picky about specifying data types. For example, the following cell returns an error because the two tensors have different data types of floats vs integers. 

In [5]:
c = torch.tensor([1., 2., 3.])
d = torch.tensor([1, 2, 3])

print(c - d)

RuntimeError: expected type torch.FloatTensor but got torch.LongTensor

The error is fixed by specifying the data types...

In [6]:
c = torch.tensor([1., 2., 3.], dtype=torch.float)
d = torch.tensor([1, 2, 3], dtype=torch.float)

print(c - d)

tensor([0., 0., 0.])


To make this process simpler, PyTorch tensors have built in methods for changing data types on the fly.

In [7]:
c = torch.tensor([1., 2., 3.])
d = torch.tensor([1, 2, 3])

print("Float: ", c.float() - d.float())
print("Double:", c.double() - d.double())
print("Long:  ", c.long() - d.long())
print("Int:   ", c.int() - d.int())

print('\nNote that these methods return copies of the tensor and do not modify it.')
print('The original tensors are still in memory:')
print(c)
print(d)

Float:  tensor([0., 0., 0.])
Double: tensor([0., 0., 0.], dtype=torch.float64)
Long:   tensor([0, 0, 0])
Int:    tensor([0, 0, 0], dtype=torch.int32)

Note that these methods return copies of the tensor and do not modify it.
The original tensors are still in memory:
tensor([1., 2., 3.])
tensor([1, 2, 3])


PyTorch is similar to Numpy, but is able to speed up calculations using GPUs. If this notebook is buing run with access to a GPU, the following cell will demonstrate how to load data onto a GPU. We will work with cloud GPU computing later on in the semester.

In [8]:
if torch.cuda.is_available():
    #Send data to GPU
    b = b.to(torch.device('cuda:0'))
    print(b)
    
    #Retrieve data from GPU
    b = b.to(torch.device('cpu'))
    print(b)
    
else:
    print("This computer does not have access to a GPU")

This computer does not have access to a GPU


PyTorch tensors support element-wise operations, similar to Numpy arrays, but dissimilar from mathematical tensors.

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print('a = ', a)
print('b = ', b, '\n')

print('a * b = ', a * b)   #element-wise vector multiplication
print('b * 2 = ', b * 2)   #element-wise scalar multiplication
print('a + b = ', a + b)   #element-wise vector addition
print('a + 1 = ', a + 1)   #element-wise scalar addition

a =  tensor([1, 2, 3])
b =  tensor([4, 5, 6]) 

a * b =  tensor([ 4, 10, 18])
b * 2 =  tensor([ 8, 10, 12])
a + b =  tensor([5, 7, 9])
a + 1 =  tensor([2, 3, 4])


Like Numpy, PyTorch broadcasts operations. The example below shows how traditional matrix multiplication is carried-out. Other operations can be broadcast to make the use seem less trivial.

In [10]:
X = torch.arange(6).view(2,3)
print('X = ', X)

w = torch.tensor([1,2,3])
print('w = ', w)

Xw = X.matmul(w)
print('X.matmul(w) = ', Xw)

print('\nNow compare to result with a re-shaped w')
w = w.view(-1,1)
print('w = ', w)

Xw = X.matmul(w)
print('X.matmul(w) = ', Xw)


X =  tensor([[0, 1, 2],
        [3, 4, 5]])
w =  tensor([1, 2, 3])
X.matmul(w) =  tensor([ 8, 26])

Now compare to result with a re-shaped w
w =  tensor([[1],
        [2],
        [3]])
X.matmul(w) =  tensor([[ 8],
        [26]])
